//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Work_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tables : DbContext
    {
        public Tables()
            : base("name=Tables")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR> CAR { get; set; }
        public virtual DbSet<DRIVER> DRIVER { get; set; }
        public virtual DbSet<TAXIORDER> TAXIORDER { get; set; }
        public virtual DbSet<TAXIUSER> TAXIUSER { get; set; }
        public virtual DbSet<TYPEOFUSER> TYPEOFUSER { get; set; }
        public virtual DbSet<USERHISTORY> USERHISTORY { get; set; }
    }
}
