//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Work_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERHISTORY
    {
        public decimal HISTORYID { get; set; }
        public Nullable<decimal> CLIENTID { get; set; }
        public Nullable<decimal> COSTFORTAXI { get; set; }
        public string TOLOCATION { get; set; }
        public string FROMLOCATION { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public Nullable<decimal> RAITING { get; set; }
    
        public virtual TAXIUSER TAXIUSER { get; set; }
    }
}
